## A.I. Assignment 5

## Learning Goals

By the end of this lab, you should be able to:
* Get more familiar with tensors in pytorch 
* Create a simple multilayer perceptron model with pytorch
* Visualise the parameters


### Task

Build a fully connected feed forward network that adds two bits. Determine the a propper achitecture for this network (what database you use for this problem? how many layers? how many neurons on each layer? what is the activation function? what is the loss function? etc)

Create at least 3 such networks and compare their performance (how accurate they are?, how farst they are trained to get at 1 accuracy?)

Display for the best one the weights for each layer.


Steps to solve a problem:

1. Database
2. Build the model
3. Establish Loss function (MSE, CrossEntropy, ...), the optimizer (GD, SGD, ADAM, ...)
4. Training
5. Evaluation

In [49]:
import torch
import torch.nn as nn
from collections import OrderedDict

In [50]:
data_in = torch.tensor([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=torch.float32)
print(data_in)

tensor([[0., 0.],
        [0., 1.],
        [1., 0.],
        [1., 1.]])


In [51]:
data_out = torch.tensor([[0, 0], [0, 1], [0, 1], [1, 0]], dtype=torch.float32)
print(data_out)

tensor([[0., 0.],
        [0., 1.],
        [0., 1.],
        [1., 0.]])


In [66]:
model1 = nn.Sequential(OrderedDict([
    ('hidden', nn.Linear(2, 2)),
    ('Sigmoid1', nn.Sigmoid()),
    ('output', nn.Linear(2, 2)),
    ('Sigmoid2', nn.Sigmoid())
]))
print(model1)

criterion1 = nn.MSELoss()
optimizer1 = torch.optim.SGD(model1.parameters(), lr=0.1)

for epoch in range(10000):
    optimizer1.zero_grad()
    outputs1 = model1(data_in)
    loss1 = criterion1(outputs1, data_out)
    loss1.backward()
    optimizer1.step()

    predicted_classes1 = (outputs1.round() == data_out)
    accuracy1 = predicted_classes1.all(dim=1).sum() / len(data_out)
    if (epoch+1) % 1000 == 0:
        print(f'Epoch {epoch+1} Loss: {loss1.item()} Accuracy: {accuracy1*100}%')
    if accuracy1 == 1:
        print(f"Model 1 reached 100% accuracy at epoch {epoch+1}")
        break

print(outputs1)
predicted1 = torch.round(outputs1)
correct1 = (predicted1 == data_out).all(dim=1).sum()
total1 = data_out.size(0)
accuracy1 = correct1 / total1
print(f'Model Accuracy: {accuracy1*100}%')


print(f"Model weights:")
for name, param in model1.named_parameters():
    if param.requires_grad:
        print(name, param.data)

Sequential(
  (hidden): Linear(in_features=2, out_features=2, bias=True)
  (Sigmoid1): Sigmoid()
  (output): Linear(in_features=2, out_features=2, bias=True)
  (Sigmoid2): Sigmoid()
)
Epoch 1000 Loss: 0.2041172981262207 Accuracy: 75.0%
Epoch 2000 Loss: 0.18509691953659058 Accuracy: 75.0%
Epoch 3000 Loss: 0.16418977081775665 Accuracy: 75.0%
Epoch 4000 Loss: 0.14699043333530426 Accuracy: 75.0%
Epoch 5000 Loss: 0.13358446955680847 Accuracy: 75.0%
Model 1 reached 100% accuracy at epoch 5305
tensor([[0.0183, 0.4979],
        [0.1512, 0.5290],
        [0.1526, 0.5352],
        [0.7633, 0.5000]], grad_fn=<SigmoidBackward0>)
Model Accuracy: 100.0%
Model weights:
hidden.weight tensor([[-2.1438, -2.1946],
        [ 1.6467,  1.5430]])
hidden.bias tensor([ 2.9691, -0.7883])
output.weight tensor([[-4.6514,  2.7701],
        [ 0.6347,  0.7991]])
output.bias tensor([-0.4259, -0.8616])


In [67]:
model2 = nn.Sequential(OrderedDict([
    ('hidden', nn.Linear(2, 5)),
    ('ReLU', nn.ReLU()),
    ('output', nn.Linear(5, 2)),
    ('Sigmoid', nn.Sigmoid())
]))
print(model2)

criterion2 = nn.MSELoss()
optimizer2 = torch.optim.SGD(model2.parameters(), lr=0.1)

for epoch in range(10000):
    optimizer2.zero_grad()
    outputs2 = model2(data_in)
    loss2 = criterion2(outputs2, data_out)
    loss2.backward()
    optimizer2.step()

    predicted_classes2= (outputs2.round() == data_out)
    accuracy2 = predicted_classes2.all(dim=1).sum() / len(data_out)
    if (epoch+1) % 1000 == 0:
        print(f'Epoch {epoch+1} Loss: {loss2.item()} Accuracy: {accuracy2*100}%')
    if accuracy2 == 1:
        print(f"Model 2 reached 100% accuracy at epoch {epoch+1}")
        break

print(outputs2)
predicted2 = torch.round(outputs2)
correct2 = (predicted2 == data_out).all(dim=1).sum()
total2 = data_out.size(0)
accuracy2 = correct2 / total2
print(f'Model Accuracy: {accuracy2*100}%')


print(f"Model weights:")
for name, param in model2.named_parameters():
    if param.requires_grad:
        print(name, param.data)

Sequential(
  (hidden): Linear(in_features=2, out_features=5, bias=True)
  (ReLU): ReLU()
  (output): Linear(in_features=5, out_features=2, bias=True)
  (Sigmoid): Sigmoid()
)
Model 2 reached 100% accuracy at epoch 621
tensor([[0.1861, 0.5000],
        [0.1613, 0.7099],
        [0.2161, 0.5183],
        [0.7320, 0.2578]], grad_fn=<SigmoidBackward0>)
Model Accuracy: 100.0%
Model weights:
hidden.weight tensor([[ 0.1377, -0.1055],
        [-0.9732,  0.9715],
        [ 0.4264, -0.6532],
        [-0.6283,  0.1339],
        [ 1.1477,  1.3230]])
hidden.bias tensor([-4.2516e-01, -2.3407e-04, -4.3398e-01,  4.5424e-01, -1.1478e+00])
output.weight tensor([[ 0.0403, -0.4401,  0.3608, -0.3990,  1.7362],
        [ 0.0815,  1.1021,  0.3033, -0.1691, -0.8567]])
output.bias tensor([-1.2957,  0.0765])


In [69]:
model3 = nn.Sequential(OrderedDict([
    ('hidden1', nn.Linear(2, 4)),
    ('ReLU1', nn.ReLU()),
    ('hidden2', nn.Linear(4, 4)),
    ('ReLU2', nn.ReLU()),
    ('output', nn.Linear(4, 2)),
    ('Sigmoid', nn.Sigmoid())
]))
print(model3)

criterion3 = nn.MSELoss()
optimizer3 = torch.optim.SGD(model3.parameters(), lr=0.1)

for epoch in range(10000):
    optimizer3.zero_grad()
    outputs3 = model3(data_in)
    loss3 = criterion3(outputs3, data_out)
    loss3.backward()
    optimizer3.step()

    predicted_classes3 = (outputs3.round() == data_out)
    accuracy3 = predicted_classes3.all(dim=1).sum() / len(data_out)
    if epoch % 1000 == 0:
        print(f"Epoch {epoch+1}: {accuracy3*100}%")
    if accuracy3 == 1:
        print(f"Model 3 reached 100% accuracy at epoch {epoch+1}")
        break

print(outputs3)
predicted3 = torch.round(outputs3)
correct3 = (predicted3 == data_out).all(dim=1).sum()
total3 = data_out.size(0)
accuracy3 = correct3 / total3
print(f'Model Accuracy: {accuracy3*100}%')


print(f"Model weights:")
for name, param in model3.named_parameters():
    if param.requires_grad:
        print(name, param.data)

Sequential(
  (hidden1): Linear(in_features=2, out_features=4, bias=True)
  (ReLU1): ReLU()
  (hidden2): Linear(in_features=4, out_features=4, bias=True)
  (ReLU2): ReLU()
  (output): Linear(in_features=4, out_features=2, bias=True)
  (Sigmoid): Sigmoid()
)
Epoch 1: 25.0%
Model 3 reached 100% accuracy at epoch 849
tensor([[0.1373, 0.4987],
        [0.1487, 0.5991],
        [0.0602, 0.7553],
        [0.5511, 0.3337]], grad_fn=<SigmoidBackward0>)
Model Accuracy: 100.0%
Model weights:
hidden1.weight tensor([[ 0.9988, -1.0094],
        [ 0.0512,  0.7408],
        [-0.3452, -0.2426],
        [ 0.9611,  0.5034]])
hidden1.bias tensor([-0.0100,  0.0023,  0.7139, -0.5069])
hidden2.weight tensor([[-0.5227, -0.6149,  0.3451,  0.0330],
        [ 1.3855,  0.2808,  0.5910, -1.0457],
        [ 0.1032,  0.1008,  0.0177, -0.0812],
        [-0.1998, -0.4417, -0.1762,  0.1949]])
hidden2.bias tensor([ 0.4159,  0.6946,  0.4707, -0.1030])
output.weight tensor([[-0.3327, -1.6410,  0.1094, -0.3736],
        [